### ISSUE TITLE
Style export not working from browser

### ISSUE THREAD

**Issue by harmonic7** [protobi/workbook#8]
I've managed to create xlsx files through node without any problems, however doing the same through the browser creates files that don't have any styling.

I used the code from example.html for my tests except I replaced calls to JSDateToExcelDate() with simple values as the JSDateToExcelDate() function wasn't included.

**Comment by protobi-pieter** [comment]
Thank you for reporting that and sorry for the speedbump.  First diagnosis question, are you using https://github.com/protobi/js-xlsx#beta?
- node:  `npm install xlsx-style`
- bower:  `bower install js-xlsx-style#beta`

`workbook` is just a wrapper for js-xlsx
- If you install SheetJS/js-xlsx (npm install xlsx) styles are not used
- If you install protobi/js-xlsx (npm install xlsx-style) styles are used

My first hypothesis is the browser is using the main branch SheetJS/js-xlsx because the docs are not yet clear.  I've delayed updating the README page thinking this branch might be merged in.  Will change gears and plan to make this project a separate maintained fork.

Or it might be an issue with use in the browser, and shd be reported here:  https://github.com/protobi/js-xlsx/issues

**Comment by harmonic7** [comment]
Thanks for your quick response. I've looked into it further and found out that I was in-fact using the master branch in the browser rather than the beta branch of https://github.com/protobi/js-xlsx

Thanks again.
